version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactions
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    container_name: api-gateway
    build: ./apps/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://user:password@postgres:5432/transactions
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  transaction-service:
    container_name: transaction-service
    build: ./apps/transaction-service
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@postgres:5432/transactions
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  processor-service:
    container_name: processor-service
    build: ./apps/processor-service
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://user:password@postgres:5432/transactions
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  notification-service:
    container_name: notification-service
    build: ./apps/notification-service
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://user:password@postgres:5432/transactions
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  postgres_data:
